export DST_URL_PUBLISH="https://jarovo:${GITHUB_ACCESS_TOKEN}@github.com/jarovo/data-iris.git"
echo "${DST_URL_PUBLISH}"
#echo "${publish_url}"
#export DST_URL_PUBLISH="${publish_url}"
#echo "${DST_URL_PUBLISH}"
